Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Office.Models
{
    [Table("Produto")]
    public class Produto
    {
        [Key]
        public int IDProduto { get; set; }

        [Display(Name = "Nome")]
        [Required]
        public string Nome { get; set; }

        [Display(Name = "Valor(R$)")]
        [Required]
        public decimal Valor { get; set; }

        [StringLength(100)]
        public string Descricao { get; set; }

        [Display(Name = "Marca")]
        [Required]
        public string Marca { get; set; }

        [Display(Name = "Categoria")]
        [Required]
        public string Categoria { get; set; }
        public Categoria Categorias { get; set; }

        [StringLength(300)]
        public string Foto { get; set; }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Office.Models;

namespace Office.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly Contexto _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ProdutosController(Contexto context, IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
            _context = context;
        }

        // GET: Produtos
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Produtos.ToListAsync());
        }

        // GET: Produtos/Details/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> AdmDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        public async Task<IActionResult> UserDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        // GET: Produtos/Create
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            var lista = new List<string>();

            var categoria = _context.Categorias.ForEachAsync((a) => {
                lista.Add(a.Nome);
            });

            ViewData["Categorias"] = new SelectList(lista);

            return View();
        }

        // POST: Produtos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create([Bind("IDProduto,Nome,Valor,Marca,Categoria,Foto,Descricao")] Produto produto, IFormFile Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    string pasta = Path.Combine(webHostEnvironment.WebRootPath, "img\\produtos");
                    var nomeArquivo = Guid.NewGuid().ToString() + "_" + Foto.FileName;
                    string caminho = Path.Combine(pasta, nomeArquivo);

                    using (var stream = new FileStream(caminho, FileMode.Create))
                    {
                        await Foto.CopyToAsync(stream);
                    }

                    produto.Foto = "/img/produtos/" + nomeArquivo;
                }

                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(produto);
        }

        // GET: Produtos/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int id, [Bind("IDProduto,Nome,Valor,Marca,Categoria,Foto,Descricao")] Produto produto, IFormFile NovaFoto)
        {
            if (id != produto.IDProduto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (NovaFoto != null)
                    {
                        string pasta = Path.Combine(webHostEnvironment.WebRootPath, "img\\produtos");
                        var nomeArquivo = Guid.NewGuid().ToString() + "_" + NovaFoto.FileName;
                        string caminho = Path.Combine(pasta, nomeArquivo);

                        using (var stream = new FileStream(caminho, FileMode.Create))
                        {
                            await NovaFoto.CopyToAsync(stream);
                        }

                        produto.Foto = "/img/produtos/" + nomeArquivo;
                    }

                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.IDProduto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        // GET: Produtos/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Produtos.FindAsync(id);

            // Delete img from wwwroot
            if (produto.Foto != null)
            {
                string imgProd = Environment.CurrentDirectory + "\\wwwroot\\" + produto.Foto;
                System.IO.File.Delete(imgProd);
            }

            _context.Produtos.Remove(produto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Todos()
        {
            ViewData["categorias"] = _context.Categorias.ToList();
            return View(await _context.Produtos.ToListAsync());
        }

        public IActionResult ProdutosCategoria(string id)
        {
            var listaProdutos = _context.Produtos.ToList();

            var novaListaProdutos = new List<Produto>();

            foreach (var item in listaProdutos)
            {
                if (item.Categoria.Equals(id))
                {
                    novaListaProdutos.Add(item);
                }
            }

            ViewData["categorias"] = _context.Categorias.ToList();
            return View(novaListaProdutos);
        }

        private bool ProdutoExists(int id)
        {
            return _context.Produtos.Any(e => e.IDProduto == id);
        }
    }
}

Controllers/UsuariosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Office.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class UsuariosController : Controller
    {
        private readonly Contexto _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public UsuariosController(Contexto context, IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(user);
        }
    }
}

Views/Admin/Index.cshtml
@{
    Layout = "Admin/_LayoutAdmin";
}
<!-- Main content -->
<div class="content container-fluid">
    <h1>Bem vindo, Administrador!</h1>
</div>

Views/Admin/Produtos.cshtml
<div class="container">
    <button asp-controller="Produtos" asp-action="Index"></button>
</div>

Views/Admin/Register.cshtml
@model Office.Models.UserRegistrationModel
@{
    Layout = "Admin/_LayoutAdmin";
}

<h1>Criar usuário</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <select asp-for="Cidade" class="form-control" name="Cidade">
                    <option value="Barra Bonita">Barra Bonita</option>
                    <option value="Igaraçu do Tietê">Igaraçu do Tietê</option>
                </select>
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Perfis" class="control-label"></label>
                <select asp-for="Perfis" class="form-control" asp-items="ViewBag.Perfis"></select>
                <span asp-validation-for="Perfis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div>
        <a asp-controller="Usuarios" asp-action="Index">Voltar para lista</a>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

    <script>
        $(function () {
            $("#Cpf").mask("999.999.999-99");
        });
    </script>
}

Views/Admin/Reservas.cshtml
@model IEnumerable<Office.Models.Pedido>

@{
    Layout = "Admin/_LayoutAdmin";
}

@if (Model.Count() == 0)
{
    <h1>Ainda não existem reservas!</h1>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Usuário
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataBusca)
            </th>
            <th>
                Produto
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Usuario.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataPedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataBusca)
                </td>
                <td>
                    @if (item.ItemPedidos[0].Produto != null)
                    {
                        @foreach (var produto in item.ItemPedidos)
                        {
                            @produto.Produto.Nome
                            <br />
                        }
                    }

                </td>
            </tr>
        }
    </tbody>
</table>