Controllers/PedidosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Office.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace Office.Controllers
{
    [Authorize]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 180)]
    public class PedidosController : Controller
    {
        private readonly UserManager<Usuario> _userManager;
        private readonly Contexto _context;

        public PedidosController(UserManager<Usuario> manager, Contexto context)
        {
            _context = context;
            _userManager = manager;
        }

        // Exibe os pedidos feitos pelo usuário
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var meuPedido = _context.Pedidos.ToList();
            var meusItems = new List<Produto>();

            foreach (var item in meuPedido)
            {
                if (user.Id == item.IDCliente)
                {
                    var itens = _context.ItensPedidos.SingleOrDefault(x => x.IDPedido == item.IDPedido);

                    var produtos = _context.Produtos.SingleOrDefault(x => x.IDProduto == itens.IDProduto);

                    meusItems.Add(produtos);
                }
            }

            return View(meusItems.AsQueryable());
        }

        public async Task<IActionResult> Reservar(int id)
        {
            // Não pode reservar o mesmo produto 2x
            string userID = _userManager.GetUserId(User);
            var mesmoProduto = _context.ItensPedidos.SingleOrDefault(x => x.IDProduto.Equals(id));

            if (mesmoProduto != null)
            {
                var pedidos = _context.Pedidos.SingleOrDefault(x => x.IDPedido.Equals(mesmoProduto.IDPedido) && x.IDCliente.Equals(userID));

                if (pedidos != null)
                {
                    // retornar mensagem que não pode reservar o mesmo produto 2x
                    return View();
                }
            }

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Account", "Login");
            }

            var today = DateTime.Now;
            var user = await _userManager.GetUserAsync(User);

            int ultimoPedido = 0;
            if (_context.Pedidos.ToList().Count > 0)
            {
                // Pega o id do último pedido feito 
                ultimoPedido = _context.Pedidos.OrderByDescending(x => x.IDPedido).SingleOrDefault().IDPedido;
            }

            var pedido = new Pedido
            {
                IDPedido = ultimoPedido + 1,
                DataPedido = DateTime.Now,
                DataBusca = today.AddDays(14),
                IDCliente = user.Id
            };

            var itemPedido = new ItemPedido
            {
                IDProduto = id,
                IDPedido = pedido.IDPedido
            };

            _context.Pedidos.Add(pedido);
            _context.ItensPedidos.Add(itemPedido);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        public void ExcluirPedido(int item)
        {
            var user = _userManager.GetUserId(User);

            _context.ItensPedidos.SingleOrDefault(x => x.IDProduto == item);
        }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Office.Models;

namespace Office.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly Contexto _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ProdutosController(Contexto context, IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
            _context = context;
        }

        // GET: Produtos
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Produtos.ToListAsync());
        }

        // GET: Produtos/Details/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> AdmDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        public async Task<IActionResult> UserDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        // GET: Produtos/Create
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            var lista = new List<string>();

            var categoria = _context.Categorias.ForEachAsync((a) => {
                lista.Add(a.Nome);
            });

            ViewData["Categorias"] = new SelectList(lista);

            return View();
        }

        // POST: Produtos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create([Bind("IDProduto,Nome,Valor,Marca,Categoria,Foto,Descricao")] Produto produto, IFormFile Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    string pasta = Path.Combine(webHostEnvironment.WebRootPath, "img\\produtos");
                    var nomeArquivo = Guid.NewGuid().ToString() + "_" + Foto.FileName;
                    string caminho = Path.Combine(pasta, nomeArquivo);

                    using (var stream = new FileStream(caminho, FileMode.Create))
                    {
                        await Foto.CopyToAsync(stream);
                    }

                    produto.Foto = "/img/produtos/" + nomeArquivo;
                }

                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(produto);
        }

        // GET: Produtos/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int id, [Bind("IDProduto,Nome,Valor,Marca,Categoria,Foto,Descricao")] Produto produto, IFormFile NovaFoto)
        {
            if (id != produto.IDProduto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (NovaFoto != null)
                    {
                        string pasta = Path.Combine(webHostEnvironment.WebRootPath, "img\\produtos");
                        var nomeArquivo = Guid.NewGuid().ToString() + "_" + NovaFoto.FileName;
                        string caminho = Path.Combine(pasta, nomeArquivo);

                        using (var stream = new FileStream(caminho, FileMode.Create))
                        {
                            await NovaFoto.CopyToAsync(stream);
                        }

                        produto.Foto = "/img/produtos/" + nomeArquivo;
                    }

                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.IDProduto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CaminhoFoto"] = webHostEnvironment.WebRootPath;
            return View(produto);
        }

        // GET: Produtos/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.IDProduto == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Produtos.FindAsync(id);

            // Delete img from wwwroot
            if (produto.Foto != null)
            {
                string imgProd = Environment.CurrentDirectory + "\\wwwroot\\" + produto.Foto;
                System.IO.File.Delete(imgProd);
            }

            _context.Produtos.Remove(produto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Todos()
        {
            ViewData["categorias"] = _context.Categorias.ToList();
            return View(await _context.Produtos.ToListAsync());
        }

        public IActionResult ProdutosCategoria(string id)
        {
            var listaProdutos = _context.Produtos.ToList();

            var novaListaProdutos = new List<Produto>();

            foreach (var item in listaProdutos)
            {
                if (item.Categoria.Equals(id))
                {
                    novaListaProdutos.Add(item);
                }
            }

            ViewData["categorias"] = _context.Categorias.ToList();
            return View(novaListaProdutos);
        }

        private bool ProdutoExists(int id)
        {
            return _context.Produtos.Any(e => e.IDProduto == id);
        }
    }
}

Views/Shared/_HeaderFooter.cshtml
@{
    ViewData["Title"] = "Office Street";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Layout/css/main.css" />
    <link rel="stylesheet" href="~/FontAwesome/css/all.css" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg menu">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand">
                <img src="~/img/logo.png" alt="logo" class="menu-logo" />
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Ver Produtos", "Todos", "Produtos", null, null, null, null, new { @class = "nav-link menu-button" })
                    </li>
                    <li class="nav-item">
                        <a href="https://www.instagram.com/Officestreet/?hl=pt-br" class="nav-link menu-button">Galeria</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    @if (ViewBag.Logado == true)
                    {
                        @Html.ActionLink(" ", "LoggedIn", "Account", null, null, null, null, new { @class = "btn btn-outline-primary fas fa-user", ID = "btnLogin" });
                    }
                    else
                    {
                        @Html.ActionLink(" ", "Login", "Account", null, null, null, null, new { @class = "btn btn-outline-primary fas fa-user", ID = "btnLogin" });
                    }
                    @Html.ActionLink(" ", "Index", "Pedidos", null, null, null, null, new { @class = "btn btn-outline-success fas fa-shopping-basket", ID = "btnCesta" })
                </form>
            </div>
        </nav>
    </header>
    <br />
    <br /><br />
    <main class="container-fluid" role="main">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            &copy; 2020 - Office Street
        </div>
        <div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>